# Generated by Django 2.2.6 on 2019-10-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerberus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcm_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='fcm_info',
            name='fcm_token',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
