# Generated by Django 2.2.6 on 2019-10-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerberus', '0002_auto_20191017_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_info',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcm_info',
            name='fcm_token',
            field=models.CharField(max_length=400),
        ),
    ]
